### ISSUE TITLE
Can I just apply this to specific resource?

### ISSUE THREAD

**Issue by phoenixg** [ryanw3b3r/nova-clickable-row#2]

**Comment by ryanw3b3r** [comment]
Not yet, but it's a very good idea! I will try to implement it tomorrow. Thanks!

**Comment by ryanw3b3r** [comment]
Sorry, I don't have time to implement it atm. I might do it if more people want it. I don't think that changing behaviour from page to page is good UX. If rows are clickable on one page they should stay the same on another. Feel free to submit PR though!
